config/routes.rb
Rails.application.routes.draw do
  resources :sections
  resources :sub_menus
  resources :top_menus

  get '/menu_tree', to: 'top_menus#tree'
  get '/sub_menus/:id/sections', to: 'sections#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :sub_menu
end

app/models/sub_menu.rb
class SubMenu < ApplicationRecord
  belongs_to :top_menu
end

app/models/top_menu.rb
class TopMenu < ApplicationRecord
  has_many :sub_menus
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    sub_menu_id = params[:id]
    
    if sub_menu_id
      @sections = Section.where("sub_menu_id = ?", sub_menu_id)
    else
      @sections = Section.all
    end
    
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:title, :description, :icon, :mode, :sub_menu_id)
    end
end

app/controllers/sub_menus_controller.rb
class SubMenusController < ApplicationController
  before_action :set_sub_menu, only: [:show, :edit, :update, :destroy]

  # GET /sub_menus
  # GET /sub_menus.json
  def index
    top_menu_id = params[:top_menu]
    if top_menu_id
      @sub_menus = SubMenu.where("top_menu_id = ?", top_menu_id)
    else
      @sub_menus = SubMenu.all
    end
  end

  # GET /sub_menus/1
  # GET /sub_menus/1.json
  def show
  end

  # GET /sub_menus/new
  def new
    @sub_menu = SubMenu.new
  end

  # GET /sub_menus/1/edit
  def edit
  end

  # POST /sub_menus
  # POST /sub_menus.json
  def create
    @sub_menu = SubMenu.new(sub_menu_params)

    respond_to do |format|
      if @sub_menu.save
        format.html { redirect_to @sub_menu, notice: 'Sub menu was successfully created.' }
        format.json { render :show, status: :created, location: @sub_menu }
      else
        format.html { render :new }
        format.json { render json: @sub_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_menus/1
  # PATCH/PUT /sub_menus/1.json
  def update
    respond_to do |format|
      if @sub_menu.update(sub_menu_params)
        format.html { redirect_to @sub_menu, notice: 'Sub menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub_menu }
      else
        format.html { render :edit }
        format.json { render json: @sub_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_menus/1
  # DELETE /sub_menus/1.json
  def destroy
    @sub_menu.destroy
    respond_to do |format|
      format.html { redirect_to sub_menus_url, notice: 'Sub menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_menu
      @sub_menu = SubMenu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_menu_params
      params.require(:sub_menu).permit(:title, :description, :icon, :top_menu_id)
    end
end

app/controllers/top_menus_controller.rb
class TopMenusController < ApplicationController
  before_action :set_top_menu, only: [:show, :edit, :update, :destroy]

  # GET /top_menus
  # GET /top_menus.json
  def index
    @top_menus = TopMenu.all
  end

  def tree
    top_menus = TopMenu.all
    
    respond_to do |format|
      format.json { render json: top_menus.to_json(include: :sub_menus) }
    end
  end

  # GET /top_menus/1
  # GET /top_menus/1.json
  def show
  end

  # GET /top_menus/new
  def new
    @top_menu = TopMenu.new
  end

  # GET /top_menus/1/edit
  def edit
  end

  # POST /top_menus
  # POST /top_menus.json
  def create
    @top_menu = TopMenu.new(top_menu_params)

    respond_to do |format|
      if @top_menu.save
        format.html { redirect_to @top_menu, notice: 'Top menu was successfully created.' }
        format.json { render :show, status: :created, location: @top_menu }
      else
        format.html { render :new }
        format.json { render json: @top_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /top_menus/1
  # PATCH/PUT /top_menus/1.json
  def update
    respond_to do |format|
      if @top_menu.update(top_menu_params)
        format.html { redirect_to @top_menu, notice: 'Top menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @top_menu }
      else
        format.html { render :edit }
        format.json { render json: @top_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /top_menus/1
  # DELETE /top_menus/1.json
  def destroy
    @top_menu.destroy
    respond_to do |format|
      format.html { redirect_to top_menus_url, notice: 'Top menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_top_menu
      @top_menu = TopMenu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def top_menu_params
      params.require(:top_menu).permit(:title, :description, :icon)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/sub_menus_helper.rb
module SubMenusHelper
end

app/helpers/top_menus_helper.rb
module TopMenusHelper
  def getSubMenus(parent_id)
    return SubMenu.where("top_menu_id = ?", parent_id)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SettingServer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sections/_form.html.erb
<%= form_with(model: section, local: true) do |form| %>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :icon %>
    <%= form.text_field :icon %>
  </div>

  <div class="field">
    <%= form.label :mode %>
    <%= form.select :mode, ['List', 'Record'] %>
  </div>

  <div class="field">
    <%= form.label :sub_menu_id %>
    <%= form.text_field :sub_menu_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sections</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Icon</th>
      <th>Type</th>
      <th>Sub menu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.title %></td>
        <td><%= section.description %></td>
        <td><%= section.icon %></td>
        <td><%= section.mode %></td>
        <td><%= section.sub_menu %></td>
        <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Section', new_section_path %>

app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Back', sections_path %>

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @section.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @section.description %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @section.icon %>
</p>

<p>
  <strong>Mode:</strong>
  <%= @section.mode %>
</p>

<p>
  <strong>Sub menu:</strong>
  <%= @section.sub_menu %>
</p>

<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>

app/views/sub_menus/_form.html.erb
<%= form_with(model: sub_menu, local: true) do |form| %>
  <% if sub_menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sub_menu.errors.count, "error") %> prohibited this sub_menu from being saved:</h2>

      <ul>
      <% sub_menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :icon %>
    <%= form.text_field :icon %>
  </div>

  <div class="field">
    <%= form.label :top_menu_id %>
    <%= form.text_field :top_menu_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sub_menus/edit.html.erb
<h1>Editing Sub Menu</h1>

<%= render 'form', sub_menu: @sub_menu %>

<%= link_to 'Show', @sub_menu %> |
<%= link_to 'Back', sub_menus_path %>

app/views/sub_menus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sub Menus</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Icon</th>
      <th>Top menu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sub_menus.each do |sub_menu| %>
      <tr>
        <td><%= sub_menu.title %></td>
        <td><%= sub_menu.description %></td>
        <td><%= sub_menu.icon %></td>
        <td><%= sub_menu.top_menu %></td>
        <td><%= link_to 'Show', sub_menu %></td>
        <td><%= link_to 'Edit', edit_sub_menu_path(sub_menu) %></td>
        <td><%= link_to 'Destroy', sub_menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sub Menu', new_sub_menu_path %>

app/views/sub_menus/new.html.erb
<h1>New Sub Menu</h1>

<%= render 'form', sub_menu: @sub_menu %>

<%= link_to 'Back', sub_menus_path %>

app/views/sub_menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @sub_menu.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @sub_menu.description %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @sub_menu.icon %>
</p>

<p>
  <strong>Top menu:</strong>
  <%= @sub_menu.top_menu %>
</p>

<%= link_to 'Edit', edit_sub_menu_path(@sub_menu) %> |
<%= link_to 'Back', sub_menus_path %>

app/views/top_menus/_form.html.erb
<%= form_with(model: top_menu, local: true) do |form| %>
  <% if top_menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(top_menu.errors.count, "error") %> prohibited this top_menu from being saved:</h2>

      <ul>
      <% top_menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :icon %>
    <%= form.text_field :icon %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/top_menus/edit.html.erb
<h1>Editing Top Menu</h1>

<%= render 'form', top_menu: @top_menu %>

<%= link_to 'Show', @top_menu %> |
<%= link_to 'Back', top_menus_path %>

app/views/top_menus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Top Menus</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Icon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @top_menus.each do |top_menu| %>
      <tr>
        <td><%= top_menu.title %></td>
        <td><%= top_menu.description %></td>
        <td><%= top_menu.icon %></td>
        <td><%= link_to 'Show', top_menu %></td>
        <td><%= link_to 'Edit', edit_top_menu_path(top_menu) %></td>
        <td><%= link_to 'Destroy', top_menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Top Menu', new_top_menu_path %>

app/views/top_menus/new.html.erb
<h1>New Top Menu</h1>

<%= render 'form', top_menu: @top_menu %>

<%= link_to 'Back', top_menus_path %>

app/views/top_menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @top_menu.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @top_menu.description %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @top_menu.icon %>
</p>

<%= link_to 'Edit', edit_top_menu_path(@top_menu) %> |
<%= link_to 'Back', top_menus_path %>